### ISSUE TITLE
add file size limit for user-inputted files

### ISSUE THREAD

**Issue by acatiadroid** [acatiadroid/wantstoparty#1]
Useful when files are user-inputted (I.E. anyone can upload files), this is a pre-upload check that prevents users from uploading files that exceed a specified size limit.

**Comment by BunkDev5674** [comment]
pp poo poo

**Comment by iiAlanii** [comment]
omgggggggggggggg

**Comment by acatiadroid** [comment]
Added in 291f7438f4c38e592abf463f5855fcc99223cd4e
